### ISSUE TITLE
Possible collaboration?

### ISSUE THREAD

**Issue by markusressel** [freenas/freenas-java-api-client#1]
Hi there,

I use FreeNAS on a personal level.
Although the new webinterface of FreeNAS 11 is pretty awesome(!) I really like the idea of providing a generic api client implementation. I have started to work on an android app some time ago to be able to quickly check my FreeNAS on the go and also support things like notifications.

To interact with the FreeNAS instance I wrote my own API client. Unlike the description of this repo suggests it uses modern libraries though like RxJava, Fuel (http client) and Kotlin instead of Java as the main programming language (because of the android background and I just love Kotlin).

Currently only API v1 is supported and even that is not tested very well and lacks implementations in a number of categories (simply because I didn't need them).
Because I don't think it is worth the effort to implement this fully since API v2 is already on the way I won`t put much effort into this anymore.

I want to support API v2 using websockets and have already started to implement parts of it even though I know the interface might change until it`s finalized. I also want to test as much of it as possible by using integration tests.

## Why I opened this issue
This repo claims to be compatible with API v1 and v2 (wip).
Looking at the code this seems like it is the goal of this repo but not the current state.
**Is there any intention from your side to continue this project?**
**And if so are you interested in collaborating on this?**

You can find my client repo here:
https://github.com/markusressel/freenas-api-client

**Disclaimer**: Since I only use FreeNAS privately and code in my free time I can't invest whole workdays into this.

Thanks for your awesome work! :smile:

**Comment by bastiao** [comment]
Hi @ markusressel. It is nice that you liked the project and it is also good that you have your own ideas to develop mobile apps to better interacting with your Storage system. That’s great! Indeed, there is an intention to continue the project and to collaborate. There is some work in progress code for websocket API to make it faster (and also using V2 API). 

The idea of freenas-java-api-client is to allow to connect with FreeNAS/TrueNAS and being able to execute operations or fetch information from the system. This will allow to interact with FreeNAS system by a Java application without know any details regarding their API, which means that if there are changes in API, the Java will be kept. I will send you an email so we can keep the fast discussions offline.

**Comment by ZackaryWelch** [comment]
@markusressel I've taken over work on this project and would like to update this issue. Shortly I'll be updating the java api client to work with API v2 for compatibility with TrueNAS 12.0. At the time v2 was still in the works but hopefully once I'm done that will no longer be the case. I'm not sure how much freenas-cli is used, but unless priorities change I'll be focusing more on updating freenas-client/freenas-entities as they serve as dependencies for the vCenter Plugin. I'm not sure how much Luis and yourself communicated since I never spoke to him about this.

I see you have a dev branch on your project you've updated a couple of times since this issue was posted. What are your current plans/thoughts on the project since 11.3/12.0 have been released? Do you still wish to collaborate and/or continue work on your end for API v2?

**Comment by markusressel** [comment]
Hi @ZackaryWelch, thx for getting back to me.

On the topic of collaboration:
My initial idea when posting, was to share my project and provide an initial, rough implementation of what I think an API client could look like, to hopefully spark new interest in the development of a fully fledged library that can be used by anyone to interact with FreeNAS/TrueNAS. I have had a bit of conversation with @bastiao about the difference in design goals for such a library implementation, and - if I remember correctly, this was over a year ago - it is not possibly to bring my goals and your goals all together, mainly due to the fact that I would like to make use of Kotlin coroutines and other "not so stable"/"modern" libraries. The conversation went stale on both sides, and I haven't looked at this repo for over a year, so I am quite out-of-date on the progress that has been made since then.

As for the state of my repo:
I plan on fully supporting API v2 through websockets only, and with the release of that, drop support of API v1 entirely to keep maintainance as low as possible.  
I have not designed a way to support multiple different API versions within the same library.
The current implementation does **not** serialize API responses to "Entity classes", instead the data is returned as a basic `JsonElement` (or `Exception`). I did this simply because it would take ages to create data classes for all the different entities FreeNAS has to offer, maybe it would be possible for me to reuse your `freenas-entities` package to improve this.

As stated in the original post, I am **only** working on this in my free time. Nonetheless it is a fun and educating project and I still like to continue working on it, although not as often anymore. Since, in the future, I will probably shift my home server software away from FreeNAS (and towards a linux based system), I am unsure about how much motivation I will have to support this going forward.

**Comment by kmoore134** [comment]
@markusressel Thanks! Just didn't know if you heard that we're also working on a Linux Based FreeNAS/TrueNAS now. Its available for early testing and development. Not sure if this would be something you'd be interested in using as well.

https://www.ixsystems.com/community/threads/truenas-scale-announcement-and-nightly-image-downloads.85927/

**Comment by ZackaryWelch** [comment]
Okay, in that case I will go ahead and close this issue, and I wish you the best of luck on your project!
