### ISSUE TITLE
build and test guidelines are missing in the readme.

### ISSUE THREAD

**Issue by hostingrajamani** [freenas/freenas-java-api-client#10]
I am a PHP developer and have basic knowledge on Java. 
Want to try it, But no idea on how to build the source code and use it.

Some basic information on how to use build, use it will be helpful.

**Comment by ZackaryWelch** [comment]
Can do. Currently I'm in the process of converting large parts over from v1 to v2 and websockets. This means I'll branch v1 support and only FreeNAS 11.2 and above can be used. Once that's done I'll update the readme and probably leave this project alone for the foreseeable future.
